[package]
name = "cargo-squatty"
version = "0.1.0"
authors = ["Filippo Neysofu Costa <filippo@neysofu.me>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
tempfile = "3.8"
